"""empty message

Revision ID: 1584613263fa
Revises: 7f5ad1acb978
Create Date: 2019-05-13 15:09:55.623124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1584613263fa'
down_revision = '7f5ad1acb978'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promo', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promo', 'image_url')
    # ### end Alembic commands ###
