"""add relationship to shows

Revision ID: 16d1bd5350c8
Revises: 41e27b7a4966
Create Date: 2019-04-04 15:30:50.261542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16d1bd5350c8'
down_revision = '41e27b7a4966'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('channel_id', sa.Integer(), nullable=False))
    op.add_column('show', sa.Column('lookback', sa.Integer(), nullable=True))
    op.add_column('show', sa.Column('order', sa.String(), nullable=True))
    op.create_foreign_key(None, 'show', 'channel', ['channel_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'show', type_='foreignkey')
    op.drop_column('show', 'order')
    op.drop_column('show', 'lookback')
    op.drop_column('show', 'channel_id')
    # ### end Alembic commands ###
