"""empty message

Revision ID: 1ec804d7553f
Revises: 16d1bd5350c8
Create Date: 2019-04-09 17:13:46.925905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ec804d7553f'
down_revision = '16d1bd5350c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clip', sa.Column('show_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'clip', 'show', ['show_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clip', type_='foreignkey')
    op.drop_column('clip', 'show_id')
    # ### end Alembic commands ###
