"""empty message

Revision ID: 292ab93fadfd
Revises: 62c439705a07
Create Date: 2019-04-25 15:15:50.882546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '292ab93fadfd'
down_revision = '62c439705a07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loop', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loop', 'image_url')
    # ### end Alembic commands ###
