"""empty message

Revision ID: 62c439705a07
Revises: 1971bc0bf8cb
Create Date: 2019-04-23 19:19:05.680504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62c439705a07'
down_revision = '1971bc0bf8cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loop', sa.Column('last_played_clips', sa.PickleType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loop', 'last_played_clips')
    # ### end Alembic commands ###
