"""empty message

Revision ID: 7736fd1704be
Revises: be8a6b4ff5bc
Create Date: 2019-04-09 21:02:23.987520

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7736fd1704be'
down_revision = 'be8a6b4ff5bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.add_column('channel', sa.Column('image_url', sa.String(), nullable=True))
    op.drop_column('channel', 'image_data')
    op.add_column('clip', sa.Column('clip_url', sa.String(), nullable=True))
    op.drop_column('clip', 'clip_data')
    op.add_column('promo', sa.Column('clip_url', sa.String(), nullable=True))
    op.drop_column('promo', 'clip_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promo', sa.Column('clip_data', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('promo', 'clip_url')
    op.add_column('clip', sa.Column('clip_data', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('clip', 'clip_url')
    op.add_column('channel', sa.Column('image_data', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('channel', 'image_url')
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.CHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'user_pkey'),
    sa.UniqueConstraint('username', name=u'user_username_key')
    )
    # ### end Alembic commands ###
