"""ADD_ADMIN_FLAG

Revision ID: 82d3f0a228e9
Revises: 6143f6ba4976
Create Date: 2019-03-18 21:21:02.144659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82d3f0a228e9'
down_revision = '6143f6ba4976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('admin', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'admin')
    # ### end Alembic commands ###
