"""empty message

Revision ID: 924b6df13270
Revises: 1584613263fa
Create Date: 2019-05-17 17:40:05.799707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '924b6df13270'
down_revision = '1584613263fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clip', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clip', 'image_url')
    # ### end Alembic commands ###
