"""empty message

Revision ID: c5b71b68c770
Revises: 812e8dd2a010
Create Date: 2019-04-23 18:51:13.971776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5b71b68c770'
down_revision = '812e8dd2a010'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('last_played_clip', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'last_played_clip')
    # ### end Alembic commands ###
