"""empty message

Revision ID: dc52d9223e61
Revises: 82d3f0a228e9
Create Date: 2019-03-18 22:41:44.763993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc52d9223e61'
down_revision = '82d3f0a228e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed_on')
    # ### end Alembic commands ###
