#!/usr/bin/env python

from app import create_app
from models import db, Show, Clip, Channel, Loop


shell_app = create_app()

shell_app.app_context().push()

from IPython import start_ipython
start_ipython()